# Generated by Django 6.0.2 on 2026-03-09 17:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0002_remove_menuitem_price_remove_order_item_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.RemoveField(
            model_name='order',
            name='total_amount',
        ),
        migrations.AddField(
            model_name='order',
            name='menu_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='qrapp.menuitem'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='cost',
            field=models.IntegerField(),
        ),
    ]
