# Generated by Django 6.0.2 on 2026-03-17 03:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0003_remove_order_items_remove_order_total_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menuitem',
            name='image',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=6),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
