# Generated by Django 6.0.2 on 2026-03-21 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0004_menuitem_image_alter_menuitem_cost_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='table_number',
            new_name='total',
        ),
        migrations.RemoveField(
            model_name='order',
            name='menu_item',
        ),
        migrations.AddField(
            model_name='menuitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.TextField(default='empty'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='cost',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
