# Generated by Django 6.0.2 on 2026-03-21 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrapp', '0006_order_status_order_table_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='estimated_time',
            field=models.IntegerField(default=15),
        ),
    ]
